spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 테이블 자동 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
